// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: "development" | "production" | "test";
    }
  }
}

declare module "next" {
  interface NextFetchEvent {
    waitUntil(promise: Promise<unknown>): void;
  }
  
  interface NextRequest {
    env?: {
      DB: D1Database;
      [key: string]: any;
    };
  }
}

export {};
